-   id: antimerger-premerge
    name: Antimerger Pre-Merge hook
    description: Informs the user about an imminent three-way-merge
    entry: antimerger-premerge.sh
    language: script
    stages: [pre-merge-commit]

-   id: antimerger-precommit
    name: Antimerger Pre-Commit hook
    description: Aborts the creation of a merge commit
    entry: antimerger-precommit.sh
    language: script
    always_run: true
    stages: [pre-commit]
